name: basada_admin
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.5 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter_screenutil: 5.5.3+2
  flutter_native_splash: 2.2.7
  google_maps_flutter: 2.1.12
  get_storage: 2.0.3
  geocoding: ^2.0.1
  firebase_messaging: 12.0.1
  firebase_core: ^1.19.1
  percent_indicator: ^4.2.2
  intl: 0.17.0
  cached_network_image: 3.2.2
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: 2.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/images/
    - assets/fonts/
  fonts: 
    - family: Poppins
      fonts: 
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
        - asset: assets/fonts/Poppins-Light.ttf
        - asset: assets/fonts/Poppins-Thin.ttf
        - asset: assets/fonts/Poppins-ExtraLight.ttf
        - asset: assets/fonts/Poppins-ExtraBold.ttf
        - asset: assets/fonts/Poppins-Black.ttf
  uses-material-design: true

